/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#106e00',
        'primary': '#efffe3',
        'on-surface': '#e0e3e5',
        'on-error': '#690005',
        'outline-variant': '#3c4b35',
        'on-secondary': '#2c303d',
        'surface': '#101415',
        'on-primary-fixed': '#022100',
        'tertiary': '#f8f9ff',
        'on-surface-variant': '#baccb0',
        'secondary-container': '#454957',
        'surface-dim': '#101415',
        'background': '#101415',
        'inverse-surface': '#e0e3e5',
        'error-container': '#93000a',
        'on-background': '#e0e3e5',
        'on-primary': '#053900',
        'surface-container-low': '#191c1e',
        'surface-container': '#1d2022',
        'surface-container-high': '#272a2c',
        'on-secondary-container': '#b5b8c9',
        'on-tertiary': '#2c3138',
        'surface-variant': '#323537',
        'primary-container': '#39ff14',
        'on-primary-container': '#107100',
        'inverse-on-surface': '#2d3133',
        'error': '#ffb4ab',
        'on-error-container': '#ffdad6',
        'surface-bright': '#363a3b',
        'primary-fixed-dim': '#2ae500',
        'primary-fixed': '#79ff5b',
        'surface-container-lowest': '#0b0f10',
        'surface-container-highest': '#323537',
        'outline': '#85967c',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '40px',
        gutter: '16px',
        sm: '16px',
        md: '24px',
        base: '4px',
        xs: '8px',
        xl: '64px',
        margin: '24px',
      },
      fontFamily: {
        'headline-md-mobile': ['Hanken Grotesk'],
        'label-mono': ['JetBrains Mono'],
        'headline-md': ['Hanken Grotesk'],
        'body-base': ['Inter'],
        'stat-lg': ['Inter'],
        'display-lg': ['Hanken Grotesk'],
      },
      fontSize: {
        'headline-md-mobile': ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-mono': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-base': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'stat-lg': ['32px', { lineHeight: '1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}